server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway

---
spring:
    profiles: cloud
eureka:
  client:
      serviceUrl:
        defaultZone: http://service-registry.195.13.10.14.xip.io/eureka/
      registerWithEureka: false
