server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway

zuul:
  ignoredServices: '*'
  routes:
    awards:
      path: /awards/**
      serviceId: award
    customers:
      path: /customers/**
      serviceId: customer
    loyalty-programs:
      path: /loyaltyPrograms/**
      serviceId: loyalty-program


---
spring:
    profiles: cloud
eureka:
  client:
      serviceUrl:
        defaultZone: http://service-registry.195.13.10.14.xip.io/eureka/
      registerWithEureka: false
