server:
  port: ${PORT:8761}

spring:
  application:
    name: service-registry

eureka:
  client:
    registerWithEureka: false
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80